--!: file: tool pool

local toolPool = {
    ['common'] = {
        'Half Muffin',
        'Strainer',
        'Energy Drink',
        'Smart Watch',
        'Boiled Egg',
        'Splatter Guard',
        'Water Bottle',
        'Piping Bag',
        'Banneton',
        'Hard Water (Kousui)',
        'Ancient Interface',
        'Misshapen Beignet',
        'Dish Pile',
        'Fake Mustache',
        'Magician\'s Hat',
        'N-90',
        'Decroded Mitts',
        'Lactase Enzyme',
        'Dough Hook',
        'Basque Cheesecake',
        'Refurbished Idol',
        'Water Cup',
        'Bottomless Fries',
        'Tip Jar',
        'Chew Toy',
        'Dress Shirt',
        'Calendar',
        'Grease of Ruin',
        'Dragonscale Ring',
        'Bansho Fan',
        'Land Cucumber',
        'Bread Board',
        'LOVE',
        'Blindfold of the Unburdened',
        'Flat Pita',

    },
    ['uncommon'] = {
        'Phone Charger',
        'Face Roller',
        'Sunscreen',
        'Mini Whiteboard',
        'Coffee Mug',
        'Milk Pitcher',
        'Meat Press',
        'Chef Hands',
        'Mummified Grapes',
        'Soft Water',
        'Coffee Ground Puck',
        'Thermometer',
        'Crushed Can',
        'Pizza Spire',
        'Portafilter',
        'Preserved Pastry',
        'Potted Plant',
        'Desecrated Idol',
        'Shutter Key',
        'Parking Permit',
        'Cat Teaser',
        'Point Card',
        'Folded Filter',
        'Stolen Rug',
        'Fine Sand'
    },
    ['rare'] = {
        'Pastry Brush',
        'Floury Marker',
        'Double Helix',
        'To-Go Bag',
        'Hoiro',
        'Picnic Blanket',
        'Croissant Flakes',
        'Scraper',
        'Meat Grinder',
        'Everything Seasoning',
        'Cooking Doll',
        'Deck of Cards',
        'Loaf Loader',
        'Pot of Ghee',
        'Work Shoes',
        'Canvas Tote',
        'Cold Brew Pitcher',
        'Memory Foam',
        'Whetstone',
        'Sticky Note',
        'Tardy Treat',
        'White Potato'

    },
    ['event'] = {
        'Electric Kettle',
        'Azzi\'s Manuscript',
        'Tassajara Bread Book',
        'Levain of Theseus',
        'Puff\'s Codex',
        'Massage Gun',
        'Shoe Charm',
        'Test Oracle',
        'Lin\'s Insurance',
        'Lin\'s Ledger',
        'Vampire Fangs',
    },
    ['shop'] = {
        'Boxing Wraps',
        'Recipe Book',
        'Baking Soda',
        'Cinnamon Roll Eye',
        'Coffee Tamper',
        'Ambiguous Furniture',
        'Prismatic Triangle',
        'Forgotten Placeholder',
    }
}

function GetToolPool()
    return toolPool
end;
